<?php

/**
 * @file
 * Implements module hooks.
 */

use Drupal\dgi_migrate\Plugin\migrate\process\LockingMigrationLookup;
use Drupal\dgi_migrate\Plugin\migrate\process\TrackingGet;

/**
 * Implements hook_migration_plugins_alter().
 */
function dgi_migrate_migration_plugins_alter(&$definitions) {
  foreach (array_keys($definitions) as $plugin_id) {
    if (!isset($definitions[$plugin_id]['idMap']['plugin']) || $definitions[$plugin_id]['idMap']['plugin'] === 'sql') {
      $definitions[$plugin_id]['idMap']['plugin'] = 'smart_sql';
    }
  }
}

/**
 * Implements hook_migrate_TYPE_info_alter() for "process" plugins.
 */
function dgi_migrate_migrate_process_info_alter(&$definitions) {
  $definitions['dgi_migrate_original_migration_lookup'] =
    [
      'provider' => 'dgi_migrate',
      'id' => 'dgi_migrate_original_migration_lookup',
    ] +
    $definitions['migration_lookup'];

  $lookup =& $definitions['migration_lookup'];
  $lookup['class'] = LockingMigrationLookup::class;
  $lookup['provider'] = 'dgi_migrate';

  $definitions['dgi_migrate_original_get'] = [
    'provider' => 'dgi_migrate',
    'id' => 'dgi_migrate_original_get',
  ] + $definitions['get'];

  $get =& $definitions['get'];
  $get['class'] = TrackingGet::class;
  $get['provider'] = 'dgi_migrate';
}
