<?php

namespace Drupal\dgi_migrate\Plugin\migrate\destination;

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\dgi_migrate\Plugin\migrate\process\TrackingGet;
use Drupal\migrate\MigrateException;
use Drupal\migrate\Plugin\MigrateIdMapInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\migrate\destination\EntityContentBase;
use Drupal\migrate\Row;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a custom destination plugin for generating entity revisions.
 *
 * This class extends the EntityContentBase class to provide a custom
 * destination plugin for Drupal migrations. It allows for the creation of
 * revisions during the migration process, and maintains revision history.
 *
 * @see \Drupal\migrate\Plugin\migrate\destination\EntityContentBase
 *
 * @MigrateDestination(
 *   id = "dgi_revisioned_entity"
 * )
 */
class DgiRevisionedEntity extends EntityContentBase {

  /**
   * The entity type.
   *
   * @var string
   */
  public string $entityType;

  /**
   * The migration ID.
   *
   * @var string
   */
  protected string $migrationId;

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition, ?MigrationInterface $migration = NULL) {
    $entity_type = $configuration['entity_type'] ?? 'node';
    $instance = parent::create($container, $configuration, 'entity:' . $entity_type, $plugin_definition, $migration);
    $instance->entityType = $entity_type;
    $instance->migrationId = $migration->id();
    return $instance;
  }

  /**
   * Helper; handle process disabling.
   *
   * @param \Drupal\migrate\Row $row
   *   Get entity for given row.
   * @param array $old_destination_id_values
   *   Old destination ID values.
   *
   * @return \Drupal\Core\Entity\EntityInterface|null
   *   The entity; otherwise, NULL.
   *
   * @see \Drupal\dgi_migrate\Plugin\migrate\destination\DgiRevisionedEntity::getEntity()
   */
  private function doGetEntity(Row $row, array $old_destination_id_values = []) : ?EntityInterface {
    if (getenv('DGI_MIGRATE_TRACKING_GET_DISABLED') === 'true') {
      return $this->getEntity($row, $old_destination_id_values);
    }

    $filtered_row = TrackingGet::filterRow($row);

    $entity = $this->getEntity($filtered_row, $old_destination_id_values);

    foreach ($row->getRawDestination() as $property => $values) {
      $row->removeDestinationProperty($property);
    }
    foreach ($filtered_row->getRawDestination() as $property => $values) {
      $row->setDestinationProperty($property, $values);
    }
    $row->setIdMap($filtered_row->getIdMap());

    return $entity;
  }

  /**
   * {@inheritdoc}
   */
  public function import(Row $row, array $old_destination_id_values = []) {
    $this->rollbackAction = MigrateIdMapInterface::ROLLBACK_DELETE;

    $entity = $this->doGetEntity($row, $old_destination_id_values);

    if (!$entity) {
      throw new MigrateException('Unable to get entity');
    }

    assert($entity instanceof ContentEntityInterface);

    if ($this->isEntityValidationRequired($entity)) {
      $this->validateEntity($entity);
    }

    if (!$entity->isNew()) {
      $entity->setNewRevision();
      $entity->setRevisionCreationTime(time());

      $revision_message = $this->generateRevisionMessage();
      $entity->setRevisionLogMessage($revision_message);
    }

    $ids = $this->save($entity, $old_destination_id_values);

    if ($this->isTranslationDestination()) {
      $ids[] = $entity->language()->getId();
    }

    return $ids;
  }

  /**
   * Generates a detailed revision message.
   *
   * @return string
   *   The generated revision message.
   */
  protected function generateRevisionMessage() {
    return sprintf('New revision generated by migration `%s`.', $this->migrationId);
  }

}
